sonar.projectKey=safe-zone
sonar.projectName=safe-zone
sonar.projectVersion=0.0.1

sonar.sources=common-security/src/main,discovery/src/main,gateway/src/main,user-service/src/main,product-service/src/main,media-service/src/main,frontend/src
sonar.tests=common-security/src/test,discovery/src/test,user-service/src/test,product-service/src/test,media-service/src/test
sonar.exclusions=**/node_modules/**,**/*.spec.ts

sonar.java.source=21
sonar.java.binaries=common-security/target/classes,discovery/target/classes,gateway/target/classes,user-service/target/classes,product-service/target/classes,media-service/target/classes
sonar.java.test.binaries=common-security/target/test-classes,discovery/target/test-classes,user-service/target/test-classes,product-service/target/test-classes,media-service/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=common-security/target/site/jacoco/jacoco.xml,discovery/target/site/jacoco/jacoco.xml,user-service/target/site/jacoco/jacoco.xml,product-service/target/site/jacoco/jacoco.xml,media-service/target/site/jacoco/jacoco.xml
