server:
  port: 8080          # angular will hit this port

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**,/users/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media/**

      discovery:
        locator:
          enabled: false

eureka:
  client:
    register-with-eureka: true    # default value
    fetch-registry: true          # default value
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost