spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/mediadb
  kafka:
    bootstrap-servers: kafka:29092
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true
minio:
  url: http://minio:9000                         # "minio" = compose service name