server:
  port: 8083

spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/mediadb    # media db name
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: media-service            # consumer group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

minio:
  url: http://localhost:9000        # S3 API port
  access-key: minioadmin
  secret-key: minioadmin
  bucket: product-images